# Generated by Django 4.1.5 on 2023-02-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=1000, null=True)),
                ('venue', models.CharField(max_length=200, null=True)),
                ('event_date', models.DateField(null=True)),
                ('link', models.CharField(max_length=900, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobPostings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jtitle', models.CharField(max_length=200, null=True)),
                ('company', models.CharField(max_length=200, null=True)),
                ('jdescription', models.CharField(max_length=1000, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('applylink', models.CharField(max_length=900, null=True)),
            ],
        ),
    ]
