# Generated by Django 4.1.5 on 2023-02-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Information Technology', 'Information Technology'), ('Electronics and Communications Engineering', 'Electronics and Communications Engineering'), ('Electricals and Electronics Engineering', 'Electricals and Electronics Engineering')], max_length=100),
        ),
    ]
