# Generated by Django 4.1.5 on 2023-02-23 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_jobposting_created_at_jobposting_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobposting',
            name='updated_at',
        ),
    ]
