# Generated by Django 4.1.5 on 2023-02-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_jobposting_created_at_jobposting_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project_Title', models.CharField(max_length=200, null=True)),
                ('Domain', models.CharField(max_length=200, null=True)),
                ('Project_Description', models.CharField(max_length=1000, null=True)),
            ],
        ),
    ]
