# Generated by Django 4.1.5 on 2023-02-24 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_mentorship'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='Domain',
            field=models.CharField(choices=[('Artificial Intelligence', 'Artificial Intelligence'), ('Machine Learing', 'Machine Learing'), ('Data Science', 'Data Science'), ('Web Development', 'Web Development'), ('Robotics and Automation', 'Robotics and Automation'), ('Robotics Process and Automation', 'Robotics Process and Automation'), ('Electricals', 'Electricals'), ('Electronics', 'Electronics'), ('Civil', 'Civil'), ('Mechanical', 'Mechanical'), ('Others', 'Others')], default=2, max_length=100),
            preserve_default=False,
        ),
    ]
