# Generated by Django 4.1.5 on 2023-02-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0010_alter_mentorship_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentorship',
            name='Project_Description',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
