# Generated by Django 4.1.5 on 2023-02-24 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_alter_mentorship_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentorship',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
