# Generated by Django 4.1.5 on 2023-03-30 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_mentorship_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='applylink',
            new_name='Apply_Link',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='company',
            new_name='Company',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='jdescription',
            new_name='Job_Description',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='jtitle',
            new_name='Job_Title',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='location',
            new_name='Location',
        ),
    ]
